import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useRef, useEffect } from "react";
import { getPositions } from "../components/singleComponents/Utils/Utils";

const Home: NextPage = () => {
  const fwdRef = useRef<HTMLHeadingElement>(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>The Tale of Abe</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/psyFav.gif" /> */}
      </Head>

      <main className={styles.main}>    
        <h1 ref={fwdRef}>THE TALE<br/> OF ABE</h1>
        <img className="moon-symbol" src="/images/moon-symbol.png" alt="moon-icon" />
        <p className="p0">I’ve traveled through lands far, far away from here.</p> 
        <div className="p p1"><h2>I’ve dispelled</h2><p>dangerous adversaries with ancient magic, using the power of my mind.</p> </div>
        <div className="p p2"><h2>As I walk </h2><p>I can’t but help wonder...</p> </div>
        <div className="p p3"><h2>Do I walk towards the light</h2><p>or do I turn back and face the world once more?</p></div>
        <footer><p>♫ Mind Flight - Flying Lotus</p></footer>
      </main>
      <audio src="/audio/music.mp3" id="music">
        Your browser does not support the
        <code>audio</code> element.
      </audio>      
    </div>
  );
};

export default Home;
